version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend
    ports:
      - 3001:3001
  db:
    container_name: database
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
